CONFIG
  ENV
    MS_MAP_PATTERN "^\/etc\/mapserver\/([^\.][-_A-Za-z0-9\.]+\/{1})*([-_A-Za-z0-9\.]+\.map)"
    MS_ERRORFILE "stderr"
  END
  MAPS
    BASEMAPS "/etc/mapserver/osm-google.map"
  END
END
